
version: '3'
services:
  app:
    container_name: todo_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - todo-mysql          
    networks:
      - my-network

  todo-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DATASOURCE_HOST} 
      - MYSQL_USER=${DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=${DATASOURCE_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - my-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - todo-mysql
    environment:
      - PMA_HOST=todo-mysql # Note the "todo-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DATASOURCE_USERNAME}
      - PMA_PORT=${DATASOURCE_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - my-network


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  my-network:
    driver: bridge